#!/bin/sh

cmake .. \
    -DCMAKE_BUILD_TYPE=RelWithDebInfo \
    -DCMAKE_EXPORT_COMPILE_COMMANDS=1 \
    -DCMAKE_CUDA_FLAGS="-lineinfo" \
    -DUSE_NVTX=ON \
    -DBUILD_TEST=ON \
    -DFETCHCONTENT_UPDATES_DISCONNECTED=ON \
    -DLMDEPLOY_ASAN_ENABLE=OFF \
    -DLMDEPLOY_UBSAN_ENABLE=OFF \
    -DCMAKE_CUDA_ARCHITECTURES="80-real"
